# Generated by Django 5.1.7 on 2025-05-02 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeEvent', models.CharField(choices=[('exam', 'Exam'), ('test', 'Test'), ('school_events', 'School Events'), ('parent_teacher_meeting', 'Parent-Teacher meeting'), ('personal_events', 'Personal events')], default='school_events', max_length=25)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, default=15)),
                ('location', models.TextField(blank=True, default='')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
